### ISSUE TITLE
怎么转的模型呢

### ISSUE THREAD

**Issue by huaxiangwangman** [Sologala/nanodet_rknn#2]

**Comment by Sologala** [comment]
HI, @huaxiangwangman ， 你可以参考一些官方仓库里面的文档 [指南](https://github.com/rockchip-linux/rknn-toolkit/tree/master/doc)。中英双语都有。

**Comment by huaxiangwangman** [comment]
速度怎么样呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dawson ***@***.***&gt;; 
发送时间: 2021年11月19日(星期五) 中午11:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Sologala/nanodet_rknn] 怎么转的模型呢 (Issue #2)





 
HI, @huaxiangwangman ， 你可以参考一些官方仓库里面的文档 指南。中英双语都有。
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Sologala** [comment]
320*320  13.3312ms  75.0119fps 这是我转换的nanodet-m的结果

**Comment by huaxiangwangman** [comment]
这么快，转的时候有坑吗，直接onnx转吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dawson ***@***.***&gt;; 
发送时间: 2021年11月19日(星期五) 中午11:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Sologala/nanodet_rknn] 怎么转的模型呢 (Issue #2)





 
320*320  13.3312ms  75.0119fps 这是我转换的nanodet-m的结果
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Sologala** [comment]
这么快是量化之后的结果，但是有一定的精度损失。

**Comment by huaxiangwangman** [comment]
好，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dawson ***@***.***&gt;; 
发送时间: 2021年11月19日(星期五) 中午11:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Sologala/nanodet_rknn] 怎么转的模型呢 (Issue #2)





 
这么快是量化之后的结果，但是有一定的精度损失。
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
